### PR TITLE
Fix for #22: stop error from `test` command

### LINKED ISSUE #22: Running with no args prints error
Steps:
 1. use fast-nvm-fish 2a5ad55
 1. run `nvm` (with no args)

Expected:
The help message for nvm is shown.

Actual:
The warning from this script is shown (not the issue here) and an error message from the `test` command:
```
nvm-fast: at least one argument is required
test: Missing argument at index 2
```

I think if you show that warning message, the script should halt because continuing without something the script states it needs is heading for failure.

Alternatively, don't worry about printing a warning and instead, set the default arg to `--help` and let the script continue. I'm a fan of this approach.

### PR DESCRIPTION
**Pull request by tomsaleeba**
Fixes #22.
I'm not sure if this is the behaviour you want but at least it gets rid of that error from `test`

### CODE REVIEW

**Comment by brigand** [comment]
Doesn't this throw from the argv access if there are no arguments?

**Comment by tomsaleeba** [comment]
Yeah, it throws from here: https://github.com/brigand/fast-nvm-fish/blob/ff47b8da5254f71663a40963dfcc96fc9d0361e0/nvm.fish#L8

A simple test case is this script:
```sh
#!/usr/bin/fish
echo 'before'
set -l c $argv[1]
if test $c = 'use'
  echo 'yep, use'
end
echo 'after'
```
Assume we save it as `blah.fish` and it explodes when you try to access that non-existant index of `$argv`, like you say:
```console
$ fish blah.fish asdf
before
after
```
```console
$ fish blah.fish
before
test: Missing argument at index 2
after
```

My goal is to stop that error message. Setting a default "command" has the added bonus of making the script more user friendly; you can run it with no args happily.

**Comment by brigand** [comment]
You need to use `(count $argv)` and not read the item if it's 0.

**Comment by tomsaleeba** [comment]
How about this approach: https://github.com/tomsaleeba/fast-nvm-fish/commit/26bef18115ef6aae190f6f491821081e58a7c99f#diff-5aa7c1aafb1d525d781f1c83ca10e0c2

It achieves the same goal as this PR but goes about it a bit differently. It does what you mentioned by branching based on the result of the count of the whole argv list, not the element at index 1.

**Pull request closed without merging**
